# Content:




* Dynamic Array with Python

In [1]:
import numpy as np

array = np.array([[1,2,3,4,5]])
print(array)
print("shape: ",array.shape)

[[1 2 3 4 5]]
shape:  (1, 5)


In [2]:
array2D = np.array([[1,2,3,4,5], 
                   [6,7,8,9,10]])

print(array2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Dynamic Array with Python

In [3]:
import ctypes

class DynamicArray(object):
    
    # initializer (constructor)
    def __init__(self):
        
        self.n = 0 # number of values
        self.capacity = 1
        self.A = self.make_array(self.capacity)
        
    def __len__(self):
        """
        return number of value of array
        """
        return self.n
    
    def __getitem__(self,k):
        """
        return number values in index k
        """
        if not 0 <= k <= self.n:
            return IndexError("k is out of bounds !")
        
        return self.A[k]
            
        
    def append(self,value):
        """
        append value to array
        """
        if self.n == self.capacity:
            self._resize(2*self.capacity)
            
        self.A[self.n] = value # append value
        self.n += 1 # add 1 to number of values
        
    def _resize(self,new_cap):
        """
        increasing array capacity
        """
        B = self.make_array(new_cap) # make new array
        
        # move old array which is inside of A to new array B
        for k in range(self.n):
            B[k] = self.A[k]
            
        self.A = B # update Array
        self.capacity = new_cap # update capacity
        
    def make_array(self, new_cap):
        """
        return new array
        """
        
        return (new_cap*ctypes.py_object)()

In [4]:
# define an object
arr = DynamicArray()

# append new element
arr.append(1)
print(arr[0])
# append new element
arr.append(3)
print(arr[0],arr[1])
# append new element
arr.append(5)
print(arr[0],arr[1],arr[2])

1
1 3
1 3 5


In [5]:
print(len(arr))

3


## Array Challenge


# Word Split Problem


* input = ["deeplearning", "d,dll,a,deep,dee,lear,learning"]


* output =   "deep , learning"

In [6]:
def wordSplit(liste):
    
    word = list(liste[0])
    d = liste[1].split(",")
    
    for i in range(1,len(word)):
        c = word[:]
        c.insert(i," ")
        
        x,y = "".join(c).split()
        if x in d and y in d:
            return x + " , " + y
        
    return "Not Match!"

In [7]:
print(wordSplit(["deeplearning", "d,dll,a,deep,dee,lear,learning"]))

deep , learning
